### ISSUE TITLE
Vue 3 Support?

### ISSUE THREAD

**Issue by chiqors** [vuevert/Vert-Core#49]
is this repo still active? do you plan to update it?

**Comment by LancerComet** [comment]
Nope, because I think for Vue 3 (also 2.7), Composition API + J/TSX is much more powerful than this.
But I believe it is not tough to make it to support Vue 3.
Maybe I will adapt it to Vue 3 if people really need it.

**Comment by LancerComet** [comment]
Please re-open the issue if necessary
